export default {
  FETCH_ALL_CARDS_BEGIN: 'FETCH_ALL_CARDS_BEGIN',
  FETCH_ALL_CARDS_SUCCESS: 'FETCH_ALL_CARDS_SUCCESS',

  FETCH_CARD_BEGIN: 'FETCH_SELECTED_CARD_BEGIN',
  FETCH_CARD_SUCCESS: 'FETCH_SELECTED_CARD_SUCCESS',

  FETCH_CARDS_BY_CLASS_BEGIN: 'FETCH_CARD_BY_CLASS_BEGIN',
  FETCH_CARDS_BY_CLASS_SUCCESS: 'FETCH_CARD_BY_CLASS_SUCCESS',

  FETCH_CARDS_BY_EXPANSION_BEGIN: 'FETCH_CARD_BY_EXPANSION_BEGIN',
  FETCH_CARDS_BY_EXPANSION_SUCCESS: 'FETCH_CARD_BY_EXPANSION_SUCCESS',
};
