export default {
  OPEN_NOTIFICATION: 'OPEN_NOTIFICATION',
  HIDE_NOTIFICATION: 'HIDE_NOTIFICATION',
  SET_NOTIFICATION_SEVERITY: 'SET_NOTIFICATION_SEVERITY',
  SET_NOTIFICATION_MESSAGE: 'SET_NOTIFICATION_MESSAGE',
};
